// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TemperatureReading.proto

#ifndef PROTOBUF_TemperatureReading_2eproto__INCLUDED
#define PROTOBUF_TemperatureReading_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace messages {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_TemperatureReading_2eproto();
void protobuf_AssignDesc_TemperatureReading_2eproto();
void protobuf_ShutdownFile_TemperatureReading_2eproto();

class Reading;

// ===================================================================

class Reading : public ::google::protobuf::Message {
 public:
  Reading();
  virtual ~Reading();

  Reading(const Reading& from);

  inline Reading& operator=(const Reading& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Reading& default_instance();

  void Swap(Reading* other);

  // implements Message ----------------------------------------------

  Reading* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Reading& from);
  void MergeFrom(const Reading& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int64 time = 1;
  inline bool has_time() const;
  inline void clear_time();
  static const int kTimeFieldNumber = 1;
  inline ::google::protobuf::int64 time() const;
  inline void set_time(::google::protobuf::int64 value);

  // required int32 temperature = 2;
  inline bool has_temperature() const;
  inline void clear_temperature();
  static const int kTemperatureFieldNumber = 2;
  inline ::google::protobuf::int32 temperature() const;
  inline void set_temperature(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:messages.Reading)
 private:
  inline void set_has_time();
  inline void clear_has_time();
  inline void set_has_temperature();
  inline void clear_has_temperature();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int64 time_;
  ::google::protobuf::int32 temperature_;
  friend void  protobuf_AddDesc_TemperatureReading_2eproto();
  friend void protobuf_AssignDesc_TemperatureReading_2eproto();
  friend void protobuf_ShutdownFile_TemperatureReading_2eproto();

  void InitAsDefaultInstance();
  static Reading* default_instance_;
};
// ===================================================================


// ===================================================================

// Reading

// required int64 time = 1;
inline bool Reading::has_time() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Reading::set_has_time() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Reading::clear_has_time() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Reading::clear_time() {
  time_ = GOOGLE_LONGLONG(0);
  clear_has_time();
}
inline ::google::protobuf::int64 Reading::time() const {
  // @@protoc_insertion_point(field_get:messages.Reading.time)
  return time_;
}
inline void Reading::set_time(::google::protobuf::int64 value) {
  set_has_time();
  time_ = value;
  // @@protoc_insertion_point(field_set:messages.Reading.time)
}

// required int32 temperature = 2;
inline bool Reading::has_temperature() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Reading::set_has_temperature() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Reading::clear_has_temperature() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Reading::clear_temperature() {
  temperature_ = 0;
  clear_has_temperature();
}
inline ::google::protobuf::int32 Reading::temperature() const {
  // @@protoc_insertion_point(field_get:messages.Reading.temperature)
  return temperature_;
}
inline void Reading::set_temperature(::google::protobuf::int32 value) {
  set_has_temperature();
  temperature_ = value;
  // @@protoc_insertion_point(field_set:messages.Reading.temperature)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace messages

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_TemperatureReading_2eproto__INCLUDED
