package com.pb.pcrm;

public class Queries {
    public static final String REQUEST_DISH_ID_LIST = "{"
            + "    \"operationName\":null,"
            + "    \"variables\" : {"
            + "        \"limit\":100000,"
            + "        \"langcode\":\"en\","
            + "        \"language\":\"EN\","
            + "        \"filter\" : {"
            + "            \"conjunction\":\"AND\","
            + "            \"groups\":["
            + "                {\"conjunction\":\"AND\","
            + "                 \"conditions\":["
            + "                    {\"field\":\"langcode\",\"value\":\"en\"},"
            + "                    {\"field\":\"type\",\"value\":\"recipe\"},"
            + "                    {\"field\":\"status\",\"value\":[\"1\"]}"
            + "                ]}"
            + "            ]}"
            + "    },"
            + "    \"query\":\"query ($language: LanguageId!, $filter: EntityQueryFilterInput) {"
            + "  nodeQuery(filter: $filter, limit: 100000) {"
            + "    count"
            + "    entities {"
            + "      entityTranslation(language: $language) {"
            + "        ... on NodeRecipe {"
            + "          nid"
            + "          title"
            + "          "
            + "        }"
            + "      }"
            + "    }"
            + "  }"
            + "}"
            + "\"}";
    public static final String REQUEST_DISH_PATTERN = "{\"operationName\":null,\"variables\":{\"imageStyle\":\"MEDIUM\",\"langcode\":\"en\",\"language\":\"EN\",\"id\":\"%d\"},\"query\":\""
            + "query ($language: LanguageId!, $imageStyle: ImageStyleId!, $id: String!) {"
            + "  nodeById(id: $id) {"
            + "    entityTranslation(language: $language) {"
            + "      ... on NodeRecipe {"
            + "        nid"
            + "        title"
            + "        fieldRecipeServings"
            + "        fieldRecipePreparationTime"
            + "        fieldRecipeCalories"
            + "        fieldRecipeProtein"
            + "        fieldRecipeFiber"
            + "        fieldRecipeMeal"
            + "        fieldRecipeNutritionFacts {"
            + "          processed"
            + "        }"
            + "        fieldFeaturedImage {"
            + "          entity {"
            + "            ... on MediaImage {"
            + "              fieldMediaImage {"
            + "                derivative(style: $imageStyle) {"
            + "                  url"
            + "                }"
            + "              }"
            + "            }"
            + "          }"
            + "        }"
            + "        fieldRecipeIngredients {"
            + "          entity {"
            + "            entityTranslation(language: $language) {"
            + "              ... on ParagraphRecipeIngredient {"
            + "                fieldRecipeIngredientQuantity"
            + "                fieldRecipeIngredientName"
            + "                fieldRecipeIngredientOptional"
            + "              }"
            + "            }"
            + "          }"
            + "        }"
            + "        fieldRecipeDirections {"
            + "          entity {"
            + "            entityTranslation(language: $language) {"
            + "              ... on ParagraphRecipeDirection {"
            + "                fieldDirectionDescription {"
            + "                  processed"
            + "                }"
            + "                fieldDirectionImage {"
            + "                  entity {"
            + "                    ... on MediaImage {"
            + "                      fieldMediaImage {"
            + "                        derivative(style: $imageStyle) {"
            + "                          url"
            + "                        }"
            + "                      }"
            + "                    }"
            + "                  }"
            + "                }"
            + "                fieldVideo"
            + "              }"
            + "            }"
            + "          }"
            + "        }"
            + "      }"
            + "    }"
            + "  }"
            + "}"
            + "\"}";
}
