package rosalind;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.StringReader;

public class Problem005Gc {

	public static void main(String[] args) throws IOException {
		String input = ">Rosalind_8958\r\n"
				+ "GGCGTGGGTTCAGGTAACAGTAATCCAATCTGAAATCCATCACAATTACGCGTTATGAAA\r\n"
				+ "TGGCGTATCACCTGGATGAGATCCAGCCTACACCAATCTACCTAATCCGCCTGGTACCTG\r\n"
				+ "GCCATAGGTCTCAGGACGCACACTGGAAAGCAGTGATTGTACCACCGTTGTCGTATCCGT\r\n"
				+ "ATGTAAGGAACATAGCCCGGTGTATATAAGCGGCAAGGAAGAGTTTTCGTACTCCCGCGG\r\n"
				+ "TTATTGCTTGTTTATATGAAAAAGGTCTGCCTGCCAGTATGCCTCATAGCTACCTGTGCT\r\n"
				+ "GAAAGCTCCAGGGTTATACCTTACGGTTCAGTTTCAATTGCCCGCAAAGGGCAGTGCCCG\r\n"
				+ "GTCCCGCTTCGATGAATAGGGTTCGGTTTCAGGGTGTCGGCTTACTTCGTTTAACCGCCG\r\n"
				+ "GTAGAGGCTCTTTTCTAATGGTTTGAGATGCAATGTTGACGTAGCGTCCTTCAAATATTA\r\n"
				+ "GTCGAATCTTTTGCAACTCCATCAATACTTTTTGTCAGGTGATTTCGCCCGAGACGGCAA\r\n"
				+ "CAGAGTAGTGCCATAGGAGAACTATCGCTACCTAGTGGCTCCTCTATGGAAACATGTAAG\r\n"
				+ "CTAAGCCTCCGGCCATTGAGTCGTGCTTAGAGAAGGATAGGCATTTAGGTCTAGACCATC\r\n"
				+ "TCGGTGATCCATTGGGACGGGAAATGGGCCCGAATCAATTTTGGTTCACGCTAAGATTCG\r\n"
				+ "GCCCGCGTTGTAAACGATCGCAGGACTCGCGAGAATAGAATACATAGCTCGAATTGCGCC\r\n"
				+ "GATAGTCTGCCGCCGGGGGCTGTGGACCGAAGTTAAAACGCCATATGCGAAATCTCGAGA\r\n"
				+ "AGCTGGACAGGCACTTTCTTCAGACGTGAGGCTTACACTAGCCTCCACCTACATTGTATC\r\n"
				+ "AACGTAGTTGGGGCTTAACGTCTTAAAATGATGTTCGAGGAAAC\r\n"
				+ ">Rosalind_1895\r\n"
				+ "GTCTCACTAAGTCGCCGAAAGACTTCTCCACCGTTGCTAGGTGCTGGAGACACCCTCCCA\r\n"
				+ "TTCTTGCTGTAGGCGCGCGATTATGACCACGGCTCTTCTCCAGCTTCAAGCACTGTGACC\r\n"
				+ "TAGTGCTTTGTAGAGACCTCGCCGAACGTACCGCTAAGACTAAGGATTGCAATTCATTAA\r\n"
				+ "AGGCCCTGTTCGGCAGCTGTCCATAGATGCGGCCGGCGGGTCCAGAGCATCCAGAGATAG\r\n"
				+ "GGACCTTGGGCTTCAGATCAACCAACGTGGAGTAGTCCCCAAGAAAGCTCCGTACATGGT\r\n"
				+ "CATGTACAGGTTTACCCCATTGGCGCATCTAAATATGCCAATGCCGGGCAGTGGATGAAG\r\n"
				+ "AAAGAGCTGGGCGCTAGAAAGACCGTGGTCAGCTACAGGTTCCGACCGAGAGAATACAAG\r\n"
				+ "GATGAGGATCTGATGGCTGATAGGGACTCAAATAATTGTACTACACACGTCACTTAGTTC\r\n"
				+ "ACTTTCGGCCCCACTGTTTCATACCTGGCTGCTCGCCCATTAATTTTTTGTTCGGGGGGT\r\n"
				+ "GGACTAACTTATTATTATATAAATGGATACTGCATCATGTCAGCTGTTACCAAATAACCA\r\n"
				+ "TTGTCCGGATCGCTGGACTGTAAATCTCTTGGAGGTGCAGCTAGCACGTTTTTCTCCAAG\r\n"
				+ "TATGAAGGTTCTGCCAAGAGCGGGAAGGTGTGGCCTCCATATCTACACGTGGTGTTCCCC\r\n"
				+ "TCGCCGCGAACTGCATAAGCAACAACTAGTTCACTTTATGGTTACGCTAGTGGACAATGG\r\n"
				+ "CCAAATTAATTAATTTTGGCGGCGCGCAGATGTTGAGAACTTTCCAAAATCACAAACGAA\r\n"
				+ "GCAACAGTTATCGTCCCGGTCGGGTTGAGCCTTTGCGATTCGTCATCTCGAATTTAAAAT\r\n"
				+ "GTCAAGCGTAACTAAGGTGGGGTCTCTTTAGGGCCTTTGA\r\n"
				+ ">Rosalind_8372\r\n"
				+ "AGATTATGTATCAGTGCCTGCCGCTCTTTCCCATATACCTGTTTCATGTATTACGGCCGG\r\n"
				+ "ACTTAAGTTGGTAATTGTTCTGTAGCCCACTCTTTACATGTACCGCTAAACATGGACTTA\r\n"
				+ "AGACCAACGGACCGTGTGACGTTGCCGCGCATCTTCCCCCTAACTGAAGGTATTAGCGTA\r\n"
				+ "TCATTAGTGCGTTATCTTTTTAAAGCGTAGTTAAAAGGGGGTTCAACAAAGCGCCTCATG\r\n"
				+ "CGGTTACTAGGGTACTCTCTAGTGAATCATGCTGAATGTCTTATATGCAAATTACTGTAA\r\n"
				+ "TTACTACCAGTCGGAGAGTTTGGCAACAACTCAATGTATAATGCGATATGCCATGGTTAG\r\n"
				+ "AAACAGAACGGACATATAATCGGCGTTGAAAGGCTCAGCCCCTGCTACCTTCGTAACAAA\r\n"
				+ "ATTTAACGGCGACGTAGTGGCCCGTCGCCAAGCTTGGCGAGCGTTCCCAGGGTTTTCGAT\r\n"
				+ "GTTATGATCAAGGACCTAGGCCTGCACAAGGGAGGGACACCGACGTAGGAGTGCTACCGG\r\n"
				+ "TTTAGTCATAGATCTTAGGGGAATTATCACTAATCAGAATCGTCCTGAACTGGAACATGG\r\n"
				+ "TTCTGAGAGAATGACCCTAATCCAGCGGTATTAAACCACTCAACCTAACACCTACCCAGA\r\n"
				+ "TGGCCTAGTGTGGATTACATCAGGCTGGCGGCCCTGTCCTGCAAAATTAACTAATGAATC\r\n"
				+ "CAGGTTTAAGCCCCATTTCATGTCTATTATCTAGACAGGCATCTGACGCAAACTCTTCTG\r\n"
				+ "GGACGAGCATTGCCACTAGATTCGGAAAGAGTGATCATCAACGACTCTTCATTGAATGCG\r\n"
				+ "AAC\r\n"
				+ ">Rosalind_1992\r\n"
				+ "AAAGTCGCTTTGGATCAGTCACATAGATTGCAAACTTTACTGATTGATTTGCACTTATCA\r\n"
				+ "TACAAATGCTCCCTAGAGCGCCTCAATTTGTTTAAAGGGTCGGTCTGAAGGCTTATGGGG\r\n"
				+ "ATACTTTCTCTCATGAACCCAACAGCCCGAGTGCGGAGAGGTAGGATTTTTATTGGGGGG\r\n"
				+ "GTTCGGCGGGAGGACACGCCATACTGGTAAATAGCAGCTCTAGAACGACGTGGGGAAACA\r\n"
				+ "ACATTACAGAACTAAACATGTATAGAACTGGGCAGACTGAGGTTGTCTGCTAGCTTACTG\r\n"
				+ "TCTAGTACGTATCTAAGTCTTAGTGATATGCGGTTGTAGTTACCGCGTCAACCCGTGGAA\r\n"
				+ "GTTCTCGGAGGTCGTATGGCACGGGTGGTGGTAACTAGCGCCCCCCGCTAAATTGCGTGT\r\n"
				+ "GTGCCTGCTGTGTACTCCTCCAAAAGGTTTGAATTATTGCGCTTCGGCCGAATAGTGTAA\r\n"
				+ "GAAAAGATCTTTATGGCTTTGTCACCGGCCCCAATAGTTATGTCTGGACCACTCAAGGCA\r\n"
				+ "AAAATTTTTGACAGTCATGAGAGGCAAAAATAATGGGTAGGGCTGACCTATTTACTCTGA\r\n"
				+ "TGCTACCGTCCTTGGATAGTCCTAAGGAGACATAGGATGCACTTCCGTACTTCCCAGAGT\r\n"
				+ "GTTGCCAGTGTCACCTGCACGCGGTGAAGTTTGCCACCCGTGGTCGTGGTTGATGTAAAA\r\n"
				+ "GGTTCATTTTATCCCACTAAAAAAAAAAGGAGGATACCTAGTCTCCGTGATAAATAGGCA\r\n"
				+ "TTAGCAAAGGCTGGAAATCATGTAGAGCTTAGGTTTCTGCTTTTTAGATACCTAAACCCG\r\n"
				+ "TAATCACC\r\n"
				+ ">Rosalind_8181\r\n"
				+ "AGATACACCGTAACCCGGAACTCTGGATACTATACCTCACATTCCTATGAGCCTTTACGC\r\n"
				+ "CAAGCACTCTTCCTACTTGCGAGTCGGGCGGGCGTCGGCCGATATTCGGTCTCCCCGTGC\r\n"
				+ "CACAGATGCTCACCCCTTGCATTTTAGAGACTCTGATCTTCGAGGCTTTCGAGGGGAGGG\r\n"
				+ "AGGTATGCTTCGAAGGTAAGTTTCGACGGTATAGTAGACTTAGAGCGGACCCACAAATTC\r\n"
				+ "CCGGGTGTATATTCGGTCGAAACCGTGTATGCCGTTATCTCGCCTAATCAGTAACCGATC\r\n"
				+ "GCAACTTGCCCAGCCAAGACAGGACGGGCCTGACACCTCCTTTGTTGGTTGAAATGATCT\r\n"
				+ "ATCCTCAATAGGGTGGTCTATGCTTATCCCGCACATATCTTAGGTGCGAGCAACTCGATA\r\n"
				+ "ATGCTTCATACATGGTCCCGCCCCCCGATCGCCACCGGACAACATCGGAGCGGAGTTTCA\r\n"
				+ "ACTCCACGCAAGCAACATCACCTAAAGTTTTTTAGAGGCGAGGCCCGGCACTCAGGAGAG\r\n"
				+ "AGGGACAAACGAAAGCCTCTAGCCTATGCCAGAACGATAGTGCTCGTTTCCTACTCAAGA\r\n"
				+ "ATGAAGGTATGACGGATCTAAGGCTGTGAAATACGATTCATGCGGTGCGGTCGGGTTTTT\r\n"
				+ "TTGGGAAAGGTCCTGGACACTAGTTGCCATTCATGGCGCCGAGCTTATCACTTATCAGGC\r\n"
				+ "GTTTAGACGCTACCAGAAACAAACCTTGTTTAAATGTTCGCTCGATAAAGAAGATGGCTG\r\n"
				+ "GGGGGTGTAGTCCCCCACACGCTACGGCCTTCAGGCGAAATCCCGTGTTCCTAGTCTTTC\r\n"
				+ "TCGATC\r\n"
				+ ">Rosalind_4381\r\n"
				+ "CTTCCGAAGAAGTTTGGGCTACCGGAGATCTCAGAGGATCGTTTGCGTCGGTCGTTTTTT\r\n"
				+ "TTATCGGATGAAAGCGCGTGATAAGACAGAATACCCCTCGGGACTTGGGTAGAACTTATG\r\n"
				+ "GCTGATGAGGTTAACTGTTTGGGGTAAGCATATTTAAAGGAACGTGGCTGCTCGCCTTAA\r\n"
				+ "CGCGACGACGTGGGGCGTGTCGGCCCGGGTTTGAGTGTACACCAACGCAGATTTGCCCAT\r\n"
				+ "CCCGCCCTTAGCTATGAGCGTCATAACGAGCATATTTTAAGACCGTCGATGCGCCTGCTA\r\n"
				+ "TTTATTATCGGAATGCCAAAAGATTCTCCCTTTAGAGCTTATCAGTATGTAGCCGTGCCT\r\n"
				+ "TGGTCGACCCCCCTTGTCTCACCTTAATGAGAAGTGCCGCGACGATGTACACAGGGTGAT\r\n"
				+ "AGTAACAGACAGTTTCAGCAAACATTGAGCATATAACTACAGGGCCCCACAATTCATAGT\r\n"
				+ "GAAGATCTTAGCCCGTATTCCAAGCAGCTCTCTAGTCTTGTTTAGTAACTCATCCAATCC\r\n"
				+ "CTACAAACATGATGGGGTCCTCCTATTTGCATAAGTTGCCACGCTCGTGTCTTCACCCTG\r\n"
				+ "TCATGTGGCTCTACTTTACAAATGGATCCACCCATCTCTATGATCATGGGCGCTTGCTTT\r\n"
				+ "CTTCCGACGATTAACCCCCAATTGTGTCGTCTTCTCCTCGTTTTCATCAGTGTACAAAAT\r\n"
				+ "CCCTCCTACGGTTCGAGACAACAGTACATCACATGTATGTCAGCACTGCGCCCCACTTGC\r\n"
				+ "GGCCCCTACGCTTCGCACCAACAAGAGTGCCGCGATCGAGCCCATAGCCAGATAATCGTG\r\n"
				+ "TCGTGGACAATGACATTTCGTTAGGCCATTGAATCGGGATTGCGTCTAACTTAACGG\r\n"
				+ ">Rosalind_8048\r\n"
				+ "TGGCCTGCAGGGACCTGATAAGGGCGTTACCATTTTGGGGCACGTTCTAGGACAAGGCGC\r\n"
				+ "CGAGTATGGGGCACCACTAAGCTATAGGGGAGCAATACGCCTGTGCTCACAGGCGGACTC\r\n"
				+ "CAACATTCGGCTGGTACCTTAATATGTCGAAGTTCCTGGGTTCTGCCTCTAGCAATAACT\r\n"
				+ "TCTGCCGATTGACTATCAGATTAACTATGTACGCCAGTTGGCTGGCCATAGGACCCCGTG\r\n"
				+ "GTTTGTCCTTCGTTATATGTATCACCGTGATCAGGGAGGCGCGTCCAAAGACTGCGTCGA\r\n"
				+ "ACCGAGTATATGTATCTCTTGGCAGGTGCTTCATGCGCAGCTGTCCTACACTAACCCATT\r\n"
				+ "TAGCACAGGTGCTCGTAACCAGAGATGTGAGTGACAAGCACTTTTGTATGTATACCATTA\r\n"
				+ "TCCCTACTGTGAGAATCGTCTTACACGCCAGGGGGGCAACACAAGCAAGGTAATCTCAAT\r\n"
				+ "TCCCCCACCAAAGTAGCGGATCCGAATCCGTCACCGGCAGATACTCACAGGAGGTGTGTG\r\n"
				+ "CAAATGTTATAACTTAACCCTCGGTGCTTCTCATGTGTTGCCTGAGCGCCGGAAGGCATA\r\n"
				+ "ACACTTACTAGACAACATCCAGTCCATAGATTACGCAGCAAAGCTCCGCTCGCCATAGGA\r\n"
				+ "GGCCCAGTATCGGTCTATAGTATGCTAATAAGCGGCCTTTCTTAGCGAAATCATGGACGT\r\n"
				+ "AAATGACTTGAACGCAGACCAGTATTATAACAGCGAGTCTAAGGGAGACTTCACCTCAGA\r\n"
				+ "AGTTGCGTGACCATAGTCTTATTCTTGCATCCGCTCACGA\r\n"
				+ ">Rosalind_6560\r\n"
				+ "ACTCAGTAAACTATTGCAGGATATTTATATATCCGCGAGAGCAGCTCGATTCGGACTATA\r\n"
				+ "GAGGTCGCCTAGACCAGGCCAATTAGCTGTCGCATGGCTTGCTCCCATTCACTGGGAATT\r\n"
				+ "GCCCTAGGTCATCTTTGTAATCCCAAGACATTGGAGGCGCATACCTAGAAATAAGCCGCG\r\n"
				+ "GGAGAAGCAACCCGTAGCGTTCCGCATGCCCCTGACGCGACAAAAAGACGAGCATTTTAT\r\n"
				+ "AGTGATTGCGCAACTGACCATATCTGGTGGACCTATTGAATTAAACTTGCCGATCTATCC\r\n"
				+ "GATACGACACAGTTGTGCTGCGACAATATAAACAAGGCCAGAATTCACATAGATCTCCTA\r\n"
				+ "TAGCCGCGGCATTGTCCTTGTAGGAAAGCTCTCTGCTAATCCCATGGGACTTAGATTCAG\r\n"
				+ "ATGAAATTAAACCATGAGAAGCAGGTCAAAAGGTCGCCTAGGTCACTTCAACGTGGTTAG\r\n"
				+ "AAGACTTTGTTCCATCGACATGCATAAATATTGGTGGAGAGAATTGCCTTCGATTTGATA\r\n"
				+ "GATGACCGTTTACTGGTCAGTGGAAATATTATCTAAATTACATGGCTTCTAATCATACAA\r\n"
				+ "ACAAACGCCCAATTCTTCAAAAGACCTTATACGAGCGTTATCGGCCCGTCGCAATGATGA\r\n"
				+ "CTGATGCGTAAGGACAGAACCACTACTCGTCGTGGCAGAGACGGCGTGGTGAGTCCCAGT\r\n"
				+ "GACTAGCGTTGACTCACTCTCCCCAGAAACTCGGTACCTTCGTCTCAACCGACGTGTGAG\r\n"
				+ "TGGATAATGGACCTGGACCGTAGGGAGTGATCGCTGG\r\n"
				+ ">Rosalind_8795\r\n"
				+ "TCCACCATTGTTATTAGGAGGAATGAACGCATCATTTCTGCTGCCCCCCAGGGCCCATAC\r\n"
				+ "CCGCGACCGTCTTATTATGTGGTTTAGTTCTACGGTTAATATGGAGACCGCTTCACTCCC\r\n"
				+ "AACTTACAGCTGTAGCCGGTTCGATCGGAGGCCTGGCTAACTGTACCTAGAAGGACTGAT\r\n"
				+ "TAGACATACGCAAACAATCGCCCTCTCGGCACTTGTTTAGTACTTCTTGAGTTCGGACGA\r\n"
				+ "AACATAGCTTTGCTCTGTGTGACTCGCGGGATCCAGTAGATGTCTGAAAAGACTGGCCAT\r\n"
				+ "CAACTCTAGATTCCATTTGTAAGGTAAGAGTTCAGAGTAGTCCTAGTCCCATATCACTGC\r\n"
				+ "TGTGAGCCGATCAGACTGAAAGGGGTTGGACATGTGCTTAGTTCGGGCATCTGACACTAG\r\n"
				+ "GTTGGTCCGGCAACACTCTTCGTAACGTCCTTATTGGATGGTCAGCTCGTTAGACCGAAT\r\n"
				+ "CTTGAACACCTCATCGTGTAAAAGGACTAAGTTCATTAAACCAGTGGCTTTTCGATGGGG\r\n"
				+ "GGTCTCTTTGTACGGACCTCACGGGTATATTTACTTTACTCCCTATGAATCCAAAATTAT\r\n"
				+ "TGATGGATGCTGGGAAGTCGGGGTTCATGTTATATATGAATTGGGAGTGGAGCTCGCCCA\r\n"
				+ "CAAGTCTCAATCTTACAGATACCAATAACAGCTTCCTCGTGACCACTAACGCAGATTGTA\r\n"
				+ "AGCTAGCTCCTCTAGCAGCTTCTGGAATCACCTGGCTGCAAAACACAGAAGCCATGTTTT\r\n"
				+ "TACGCGCTCGTTGAAGCAGACGATGTGGCACTCCGCAGTTGTTCCAAAAGTCTGCGGAGA\r\n"
				+ "TGTAGGAAATACGAAGATACGCCAGGCTGAGGGGGGTCCCTCACAACAGG\r\n";

		double maxGcContent = 0;
		String maxGcContentName = "";
		try (BufferedReader reader = new BufferedReader(new StringReader(input))) {
			String name = "";
			StringBuilder dnaBuilder = new StringBuilder();
			String line;
			while ((line = reader.readLine()) != null) {
				if (line.startsWith(">")) {
					if (!dnaBuilder.isEmpty()) {
						double gcContent = getGcContent(dnaBuilder.toString());
						System.out.println(name + " " + gcContent * 100);
						if (gcContent > maxGcContent) {
							maxGcContentName = name;
							maxGcContent = gcContent;
						}
					}
					name = line.substring(1);
					dnaBuilder = new StringBuilder();
				}
				else {
					dnaBuilder.append(line);
				}
			}
			if (!dnaBuilder.isEmpty()) {
				double gcContent = getGcContent(dnaBuilder.toString());
				System.out.println(name + " " + gcContent * 100);
				if (gcContent > maxGcContent) {
					maxGcContentName = name;
					maxGcContent = gcContent;
				}
			}
		}

		System.out.println("Max: " + maxGcContentName + " " + maxGcContent * 100);
	}
	
	private static double getGcContent(String dna) {
		long gcCount = 0; 
		for (int i = 0; i < dna.length(); i++) {
			char base = dna.charAt(i);
			if (base == 'G' || base == 'C') {
				gcCount++;
			}
		}
		return (double)gcCount / (double)dna.length();
	}

}
