package rosalind;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.util.Map;
import java.util.Map.Entry;

import org.biojava.nbio.core.sequence.DNASequence;
import org.biojava.nbio.core.sequence.io.FastaReaderHelper;

public class Problem010Cons {
	private static class ConcensusMatrix {
		private long[] g;
		private long[] a;
		private long[] t;
		private long[] c;
		
		public ConcensusMatrix(int length) {
			g = new long[length];
			a = new long[length];
			t = new long[length];
			c = new long[length];
		}
		
		public long[] getG() {
			return g;
		}
		
		public long[] getA() {
			return a;
		}
		
		public long[] getT() {
			return t;
		}
		
		public long[] getC() {
			return c;
		}
		
	}
	public static void main(String[] args) throws IOException  {
		String input = ">Rosalind_3232\r\n"
				+ "CCTCGAGGGCACTTACCCAGTTGGGCCTAACCTCAGCATCCCAGACCTAAAGTACGGCAG\r\n"
				+ "GACGAAACTAGTAGGAGGACTACGTGTCGTCGGCTTCCGTAACCCATAATCAAGATGAAA\r\n"
				+ "GTGATAATGTTAAATGGCGATCATCTAGCGCATATGGGTCGCCCTGTGAGAAGAAACCAT\r\n"
				+ "ACCCGCCTTGAGAATAGCTGCGGATTAGTGGGTACGGCAACTTTCTCGCAACCTAGGAGT\r\n"
				+ "GAGTGTATGCGACGCTCATCAGCTCTTCCGTTTCCTTACTGCGTAGACAAGACTTTCACG\r\n"
				+ "CGGTGACTCGCTCTCACATTCAGAACAAAGACCATCCCCACACTTCGACCTTAGTGTCAC\r\n"
				+ "TTACCATAAAAGTACACTCGCGGGCGGTCTGCATTTTTTGTGCGCTACATTACTATGTAA\r\n"
				+ "AGGTCTGCATCCAAAAGCATAGTGGGGTAATAGAGTTATAAGCCAACGGGTCCTCACCTG\r\n"
				+ "AGCCTGGTACCTATCAGGTATTGCTCTTATCTATTGAGCCAACTCCATCCTTTCGGACAG\r\n"
				+ "AAACACACATCTGCAAAATGGCTTCCTCGTCGTTTTGCCAAATTATGAAATTCCTCTGTG\r\n"
				+ "ATGAACAGCTGACGTCCGAAATGCCTCGATGAGTTAGAAGCTGTGATAGCCGAGCGTCCG\r\n"
				+ "CTGTAAAGGTGCCCGGATTACAATGTCTGGGTTTGAAGGAGCAAGTTATCACGGTGCGCT\r\n"
				+ "CGCTACAGCCCCGTTCCGGGATTGGGTGCGGGTCCTAAACTGTATGTTAGTTCCCGTCTC\r\n"
				+ "TACCTTTGTCATGTAGCTTATCATGGCTTGTTCAAACTGCGACTTATCGAAACCGGGATC\r\n"
				+ "CGCAAAATACCTAACGAGTTACTCTAAGAGGCAATCCCCACAAGACGATCTTTTTATTAA\r\n"
				+ "TGCACATCGCATGATGTGATCCCACGGTCCATCGCATGCTCATGGCGCCGGGGCTGTTCA\r\n"
				+ "ATTATCCGAAATCAAGTTTGAGATAG\r\n"
				+ ">Rosalind_4947\r\n"
				+ "TACCAATTCCGTGTCTCCCGTGGCCGCTCACTCTGGCCGACAACCTAATGTTTTACACGT\r\n"
				+ "CTTCTAATTAATCTTCATGGAGCACAACACGTTAACTGACATGACTATTTCTGGACCACC\r\n"
				+ "TGACGCAGAGTGGGAAGGTACGCACGCTACCAAACAAATTAATAAGAGAGTACTGAATGG\r\n"
				+ "TCGACAGTCCACTACTGAGAAGGGGGAGTGCTGTGTCCAACAGTCTAACTTCCCACTGTG\r\n"
				+ "TCTCTGGACTAAACATTTGGTATAGATATCGCTTGGCCGTTTCGTACTAAAACCCCTATT\r\n"
				+ "ATGCCTTACACATAATGTACAATCAAACCAGGCGAAGCAACCGACGAGCGGTAGTGTTCG\r\n"
				+ "CAGACCTGGGAGCATACTTCCTAGGTCATTACGGGACGGCTGCTCACCGGATCCGTTACT\r\n"
				+ "GGCAGCTTATGTATATTAGGCCTTTTTGCCAACTAAAGCCATGATAATTACCTAAGGGAA\r\n"
				+ "TGTTTACCCGTTCCCGGCGGGCTCGGTTCCAAACACCGAACCCTCCGCATGTGATTTCGG\r\n"
				+ "TCCAGGCACTGTTGGACTCCCCAAAAGATGCTCACAATTTGTCCGGGTCAGTATATCGTA\r\n"
				+ "CCCTGCAGGTTTGGAGGCAGAGATGAACAGTCATAGGAGTTCACACCGTCATGTGTACAT\r\n"
				+ "ATACAGCACCGCTCTTCGCCCTCTTAAGACCACTATCGGGACCATACGCAGTAATGTCGA\r\n"
				+ "CGCCGCATGCGGCGACTTTCGAGGTCGGCAACGTCCTCCTCGTACGTTAATTAGGCCGCA\r\n"
				+ "CGTTGGGATTTGAAGCTTAACAAGTGTCTTAGAATAACCATGTGACTTGGGTCATCGTGG\r\n"
				+ "GTGCCCCGCCGCCGCGCCGCCTTAAAACTAGAAAGTTGACCTTTCTCAGTGGCTAGAAAA\r\n"
				+ "TTCTGTGCTGGCCACCCTCCCAATTGTGCCACTCATTCATGAAGCTAAGTCCACCGAGGC\r\n"
				+ "ACAGGTTATCGTATGGTCCGGGCGTT\r\n"
				+ ">Rosalind_9261\r\n"
				+ "AACTACTGTCGCGCACTTCGAACAAACGAGATTACCCACGAAACCTTCGAAACGGCGGTG\r\n"
				+ "CAAGTGCAAGAGCTTCAAAACACTCGACTGCTCAACTGCAACATAGTCTAAATAGACTTG\r\n"
				+ "TTGACACTTTGGCCAACCTATATCGGAACTGTAGGTACGGCTATCGGCTAATAGAAAAAG\r\n"
				+ "CAGGGCAAATCTGTAATGTCGCTACACTCATTAGAACGCAGGTATGGAAGCTCGATACTT\r\n"
				+ "AGGTCGCAGACCGACGCTTCAGACCAGACAGCCCATTCCCTCCGCGACGCTCACTGCATG\r\n"
				+ "GTTTGGGTAGAAGTTATGACTTCTACTTCAACGCCCTGGTTGACTTAGACGATAAGATAG\r\n"
				+ "AGCAGTCCGCACGTCTAATGTGGATCCGGTCAATCCCAGGGATACGAGGATACGGCGCCA\r\n"
				+ "TCAATGTCCAGCGTGACGAGCTCCTGGCTATCAGAAATCACAAAGACTGTTATCCATTTT\r\n"
				+ "TGTCGAGTTTGAAACAGACCTGCCGGCCGTCCGGCCCGACCTATGGAGGCACCAACATCG\r\n"
				+ "CTTTCGTTTAACCCGACGCCTGGGCATGTATGGATGATATGTTGTACAGCTTAGCTATGC\r\n"
				+ "CGGTGACATTCGTGTGAGTTCCTAACGGTTCTAAGGGTACATCATGGAAGTTTCTGTTTG\r\n"
				+ "GCACCCTACGCAATCTGTGGGAACGACGAGGTGCTGTCACAGCTAGTCTCCGTTGTTTCT\r\n"
				+ "TGAGTGATTGGATCTCAATCCTCCGGATTCACACCCCGCCGGCCCCAGTCACAGTCCGCA\r\n"
				+ "ATCTATCGTGGGGGTTGAGTCCTGTCAGGAGTCTGCTACATCGCTTAAGGTATGCTGAAC\r\n"
				+ "CAAGGTGGGGTGGCTTGCTCGGCGTGTGAAGAGCAGTTCTATGAACCCAACCCACGGTAA\r\n"
				+ "GGACTAACATTTTCTAACTTACAACTCATCTTAGGCTCGTTCAAAGTTAAAAACACCCTA\r\n"
				+ "TTATAGGGCCGTTAACCGCGATCTCT\r\n"
				+ ">Rosalind_9140\r\n"
				+ "TCTGAGGGGGAACGTTGAACCTGTTGCTAGTCAGGTTCTGCCATTGAGTGGTATAGCCTA\r\n"
				+ "GGCCTTTCTGGATGCTCGCTGGAACAAGTAACCCCCACAGGCAAGGCCGAGGAGTAACTG\r\n"
				+ "TGAGAGGATGGATACGACCCAGGGAAGTACTCGGCTCCCTCCCCAATCGGGTAGGAACGG\r\n"
				+ "TTCATGGTGAGAAATTTCCATCGCCGACCAGAGGGGCTAATGGTTGCCGCGCGGGCAGTG\r\n"
				+ "TCCGGCTACTTGAGGAGGTGAATATAGTTCTCAACAGTTACAGCGAGGGCAGGCTACCAT\r\n"
				+ "TCGAACAGATCTCTGAGCACCTTTGCCAGAGCGGCGCGTTTTGTACAAGCAGGAATTGGG\r\n"
				+ "CTTTCCGAGCCGTATGGATGAGTTAGGAGGGGGTCTGGATGGAACTCCGCGGGCCCCACT\r\n"
				+ "TTGAACCGCTTGAGGTCTTTGTAGAGGGTGGAAAATTACCTTGTCAGCGCTTTTAACAAG\r\n"
				+ "CTGAAAGGTGAAAAATATCACGATTTTTCTACTTGCCGGCACTGATCACGCCGCTCGCGA\r\n"
				+ "GCATAGAGAATAAAATTCCCCCTCACTGACATCAGTCGGCCAAGCGTGGAGACCGTGGCG\r\n"
				+ "ATAGCGCACCACTAAGGCGCATCTGTTTGAACGCTCGTCAGGTCACGCGAGCATCTCTAG\r\n"
				+ "TGAGCAGAGATTCACTTCTAAACGTCACCCTCGACCGAGGCTCTTGGCGACCCTCCCGAT\r\n"
				+ "GGAGACACATGAGTCGACCTTCTATTGACGCTGATGTGATGAACAATTGCTCCTTCTTCC\r\n"
				+ "CCCACCTATGATGGGGGAAATGGCCTTTTGCCTCTCCTGGCACAGACTTTGTTTCTTGAG\r\n"
				+ "TAATATAGGACGCGAATTTGCTCTTGAGCCTAGAAGAGGAAGGAAGGCTTGACGGAACTC\r\n"
				+ "GATAGGCGTCAAAGACTGGGGGACCCACAGTCGTACGCCATCGATTTCCACGGCTCCAGC\r\n"
				+ "GGATTTAGAAGTCGGTTTCAACTGTA\r\n"
				+ ">Rosalind_2847\r\n"
				+ "CGTCTCTAGCCCTTGCTCCCCAAGAGACCGGGACCGTGCAAAAGCTAACGTAACATTGCC\r\n"
				+ "ATTGCAGAAAGGAGACAGCCAGCGATTGAAATAGCGGTCCTGCGATCATACCGGATTGAT\r\n"
				+ "TTGCCTAGGTCCACCTACTGTTAAGGCTGAAGTCGTGCGGATGACATGTATTAAAGGTGT\r\n"
				+ "CGTTAAACGGTGTAGGCGCGCCGACTGAATGTACGAGCGTCGTTTTCGATGAAACTTCGC\r\n"
				+ "AGATCTTTCGCACAACAAGATTCGTTATATTACCTGAGCGAGAAACTCGCACTAAGTTGA\r\n"
				+ "CTCTCGACTTTTAAGAGGTTGGAGTACAAAACGCCCCAGTTACCGTCCCATCGCCAAGCC\r\n"
				+ "ACAGACCTCTCATTTAAATGGACGTAAATTGTCTAATTAAGTAGTTTAAGTGCAGACCCT\r\n"
				+ "TTCTCCATCCGCCGAGAGGATCCGCGGGTTTACGTACCTGCAGTCTTTAGGTTGTGTCTC\r\n"
				+ "CCCGAATACTTATGACAGCTCGAGGAGATCTTTACTCCATCGGCGGTTTTTAGTACCAAC\r\n"
				+ "TAGGACTGGCTCCGTGGCAGGGATTGTTCCGACGATCAGAGTCTGGATCTTCTGCTAGAA\r\n"
				+ "CAAATATAAGTAGTACAGGGATCTGTGCTTCAATACTATGCTGTAAGCTAGCACAAGAAC\r\n"
				+ "CATAGTCGGGTCCTTTAGCCCATCATAGATAATTCCAGGGTAAGCTGGCCTCCGGATGAA\r\n"
				+ "CGTCCTATGTTCCCCAAGGACGAAACGTCTGGTAGGGTAGTCTTAGTTTCATTTTTGTGT\r\n"
				+ "ACTCTCAGTACGGACGTTAGGTCAGGAATGCACAGGCTGGGAAACCGGTACCTGAGACCT\r\n"
				+ "GTACATTCCGACTTTGTATGGGTTGTGGGGCAGTACGCTTATTCCCGTTCAACATATAGT\r\n"
				+ "AGGGGCCGGTGATGCTTGGGAGGTTGTCGCATGAGTTCTGGCTAGCCTGCTCCAACGATC\r\n"
				+ "AATGGTCTTTATATTAGCTTATCAAG\r\n"
				+ ">Rosalind_9355\r\n"
				+ "TATCTGAATTCAGAGGTAAATTTAATACGGCTCGTCGACGGTATTTCCCACAACGTAAAT\r\n"
				+ "TAGACTTTGATCGATAGTGAGAGTCCCATTCCTCTACCTAAAGGGGAAGTTCCGTGGCCT\r\n"
				+ "AGTAGACAATTGCTCTTAGCAGGGCGTTTGTAGCGAGTGACTTACGATGCTCCAGTTCGT\r\n"
				+ "TGGAAGTAAAGTAGCCATCTATTTAGCCCCCTTTGGTTTCGGCGCTTGGAGAATACGTCA\r\n"
				+ "GCAGTCGAATCCAGAGTCTCCCTGTCGGATGAGGCTTGGAGCCCGATCGTCGCTAAAAAG\r\n"
				+ "TGGTAAAGCGATTTTACCACCCTGAAAATCCGGCTACTTTCCGAAGCCCGGCGATAGCTC\r\n"
				+ "TTCAGGAGCAGCTGTTCCTAAGGCAATCTGTTATTAGTCGGACTGCCGCAATTAATACAG\r\n"
				+ "GGCCAGACTACAATCATGCTAGTCAACGCGACTACTGAGAAAGAAAGGATATAGCTTAGA\r\n"
				+ "TGGTTTACTGGGTGACTTGGAAGGGAATTTCGGGGACTTTCAATGCGACGAGAGAGTGTC\r\n"
				+ "CTAGGTAACCCCTTCTAATCTCAAGACCCCAGTCCGAAACTGTTAAACACCTGATGTACC\r\n"
				+ "ATGTGCCGCGATAGGCAACGCTGCTCTATACGGACTGCTTACACTTCTACAACTATGGCA\r\n"
				+ "GTGAGCATTCTCCTCCAACATCCTAACCTTCAACTTTAATGTTTCACCATTATAGACTTC\r\n"
				+ "AATTTACTACCCCGCCTGCATGTAAGGACGAAGTGTCGAGCAAAGGTATCCTGCACAACG\r\n"
				+ "TGAATTAGTAGCCCTAGACTTCGAGTCGAAACGCAAGCTCAGGTTAATTGTCGCGATCTC\r\n"
				+ "CCCAGTTCAGGTCATCCTGGGCGGTCTATCAAAACGACGCTTGTCAGGCTTCAGCACTGA\r\n"
				+ "ATGTAGCGATCCTGCACTATCGTTCACCAGCCCCTCGTTACGATAGCTGGACATCATTGC\r\n"
				+ "AACCGCATTTCCACCGCAGCCTATGC\r\n"
				+ ">Rosalind_4470\r\n"
				+ "TGGAACATCTCCCTAATAACTGGTCATTGTTGAGCAGTCTTACACTGTTCGGATCTACGT\r\n"
				+ "ATTCTCCCGGTTACATGTCCAAATTGTGTATGCGCCTAGACCCAATGGGAATAATGCCTT\r\n"
				+ "AGGCCAATTCAGCCCGCACTGGCGCCCTGTCACGCGAGCTTAGGATGCGACGGAGTAGTT\r\n"
				+ "GTAGTGCCCAAACGTCTCCACATGCGATATTTGACCCGTGGGAAGCAACTTAAAGCAGGT\r\n"
				+ "CCTGCGCTTTATTAGTTGAATGTGTAGCTTGAGGACGAAGGGCACAGGCTTAACACGGTG\r\n"
				+ "TCGATGGCACCTAGCGAGGTAAAAGAGACCGTGTGATTGAGCTGTAGATCGCGCACAAGA\r\n"
				+ "ATACCTAACTCTACGTGCACCAAGGCGTATGCAACTTTCGGCCTCAACGGGCCTGTACCG\r\n"
				+ "CCAAGCTCTCGGCGTATACCGGGTATGACCCACTTGTAATATGAAATTCGCAGTCGATGA\r\n"
				+ "ATAACGAGACGCTCTTGACGAGTACCTGACTGCCAGCAAACCTCTGCCCGTAAGGACGCA\r\n"
				+ "CCGCTTATGCTAGCCAACTGGTACGCCTTAACAGGTTTTGGAGACTACGACGGATGTTAT\r\n"
				+ "TTCAGATAACCTAACATATCAACAACGCTAATTCGATAAAGTACAAGATATATTTATGCA\r\n"
				+ "TCGCTGATAAAGCAGCGAGGATTCTCATATATGAACGCATTGAGTTGAACCTCTAATATT\r\n"
				+ "CCGACAAGAGTATAGCTTCTTTCAGTTGGCAGGAACTACTCTTCGATTTACTGGCGAGAG\r\n"
				+ "TTCAGACCCGCGGTTAGGAATCCTCGTATGTTCAGCAGGCTTCTCCTAACCCTTACGCGA\r\n"
				+ "CCTCCGAGAAGCCTGAAGGGAATCCATACCCATTCGCCTTCCGATGTCATGTCTCTGATT\r\n"
				+ "ATATCGGAACGCTCCTAGAACGCCGGCCGCATTGGTTTGAACACCTTCCAGCACCCGGGT\r\n"
				+ "CTATGTACGTTCTCTCGTGTCGCGCA\r\n"
				+ ">Rosalind_5564\r\n"
				+ "TTCCTATTTTAGCGACACGGGGTTAGTGGGATTCGGATAGACGCCGCAGATCGGCGCATC\r\n"
				+ "GCCTCATTTGGGGAGTATGCATATGTCAGTCGTCGATGACCCTGCGTCTCTTGCTCATGG\r\n"
				+ "CCCTGGAGGGTGCGCGCAACTTACGGAACCAAAGCTTCTCAGTCCGAATGCTGGACACAC\r\n"
				+ "CCCGAGACCCCACCTGAACCATCACAGTGTAGTTCCTGGATTAATAGCCTTTACGAGGGT\r\n"
				+ "AATGCCTTAAGCTGCCCTTTCCGGACGTCCCTGATTATCAAACGAACTAGAAACCAAAGA\r\n"
				+ "GCATCTCCCTTGTGTTCGATCTGTCGTTGGATACGAGCAAGCAGCCCACCAGTACGTGTT\r\n"
				+ "GGTTACCGTCTGACAGTTGGTGTAACCAACCGCAGGCGGAGAACATCACCATTGACAGAT\r\n"
				+ "GCTATAAAGGCGGAGCCGAGACTTCAACGATTAACAAGACGAAAAGCCCTCGGAAGTACG\r\n"
				+ "AGTACCGATAAGCAATCGGCGAGCCGCCTGCGGGCCCGAACCTTGCGCCTTGTACTGACG\r\n"
				+ "CCGTTCAAGCAACCTACTCTGCTTCATTCCTTGCTGCTACTAACCAGAGGCCCGCTTCCC\r\n"
				+ "TAAAACTATGAGTTCTTCGGGGGAATGAGTTCCATTCCGAATGTTTGACCGTCTGAAAAC\r\n"
				+ "CTTGAATAGTCCTAGATGAGCTTAGCTCCGCCGACTCTACGTTAGATAGCTGATTTTAAA\r\n"
				+ "GCTTTGCCGCTGTCAACCGGACTCCCGGATTTCCGCTAGAACGACAGTCAATAGGTCTTG\r\n"
				+ "AGGCGATCGTCGTGGGCTTAGCGATAAGGCGGAGGGCCGTAGGCTATTCCGCCTGCTGCA\r\n"
				+ "CGCGTAATCCTTCAAGTTCCTTCGCGTGGGTTTCGAGCAGGCTGCGCACCAATATAACAC\r\n"
				+ "GGTAACGGGGTCAGGGCAGGAATCCTTGCCCGAATCATTAGGGATACCGTTTCCCCGGAT\r\n"
				+ "TACCGAATGTGTTCTAACGACAGGAA\r\n"
				+ ">Rosalind_0281\r\n"
				+ "CGGGTCATATGTTCTATGTGGAACAAGCGTATAACACGGATGTTGCGTAGATGGGGGCTG\r\n"
				+ "ATCTGCCAAGCAGTTTGTGTCGCGCATGTTTGATGCGGAGGAGTTACGTGGTATGTAGAG\r\n"
				+ "TTCTTTATCCTTTTTTCGGCATATCAATCGCGAAGCGAGTCATAAGGTTGTTAAGGTTTC\r\n"
				+ "CCTATGAAGTTAGGAGGTGACGTCCGGACGAAAAGTCGCAGAAAAAGCCATAGTAAGCAC\r\n"
				+ "GATAGAACCCGTATTAACGACTGTGTGTGGGCACGACCTAGCCATTTGCTCAAAACCGCC\r\n"
				+ "GCGCGCGCACTGATGAAAGGGGCCTACTCTAATACCACGGCAGATCGCTATGTTTGTGGT\r\n"
				+ "GCTGCCGCATTCGGTCAACTGGACGGGGAAAGCATTTATGTTCGCTGCACCACTGGTGAG\r\n"
				+ "CAGCGAGACTGATAAGGTCGTTGGCAATACTCATGAGTTCGAAAGTCGCTATGGTAGTTT\r\n"
				+ "TCGTTTACCGCTTATCGCTCCGAAGCTTATGAATACTAATCTGACAAGGATATGTGGTCG\r\n"
				+ "AGTTACGTATCTGATTCCAAAAGTATCCATAAATGACAGCGCGGCTATGAATAATCCCTT\r\n"
				+ "TGCTTAAGGCCAGGGAAGGTGCATACATAAGCCCAATACTAATGGAGCTCGCAATCTTAT\r\n"
				+ "AAGGGTTACATTTGCGGTTTGCCGATCAAGAACAACAGAGGAGCAGACCGTTAGATATCT\r\n"
				+ "TGTTACGAAAAAGCATGAGACCGACGAGTCAGTCCTCTCAGCTCACCATAACTCAGCGTG\r\n"
				+ "GAATTCTCGAGTTATCGCACCTCGAACAGGCGAGCATGCTAATCGTCACAACTGTATAGA\r\n"
				+ "AGTTACTGCGTACTCGTCGTCGGTTTTGGCCGAACGATGACTACATTTCCAAGGTTGGGG\r\n"
				+ "CCCCCATTCTTAGTGAAAGCGTATCCCTTCTGTTCAAGTCGGAGAGCATTGCTGCTTAGC\r\n"
				+ "GGCCGGGACGAGCCATATACAGATTC\r\n"
				+ ">Rosalind_0588\r\n"
				+ "GCAACCACACACGCATAGACCAGAGGAGACCCACATGTATCACAGTGCCGACTCCAATAG\r\n"
				+ "ACTGGGACCCAGCTCATACACGGGACGGTATCCGCGAGTCGATACACAAGTCCCGGTGCT\r\n"
				+ "GGTTTATGATAGAAGGTTGGAACGAGTCCCGTGTATATACCGCCAGATAATATCTTGGGA\r\n"
				+ "CTCATTCCGGAGTGTTACCGAATCCGATATAGCACGAGTTCTTCGCGGCAACACTCTAAA\r\n"
				+ "AGGACCGGGCTCCTACACTAGCGTTTACTAGGAGCCTGAGGTTCACGGGTTGGCAGGGGT\r\n"
				+ "CGGTATGGACGTGTATCCCATTTAGTCCGTAGGTGGCTCGCATCCATCCTCGGGCAGGGG\r\n"
				+ "TGGTTGGTTGTCTGGCTAAAAAGAAGGCATCCGCAGGAGTTGTGACGCGTCAATCCGTAA\r\n"
				+ "TCTCCTGTCCGAAGCATTGCACTACCGTCGAAACCTTAGCAACGCGACCTTTGGATATCG\r\n"
				+ "CGTCTACCAGCGAAGGTCGTTACGAGACGCTCACTCTGTTGAAAGCTATACATTGCCTTG\r\n"
				+ "GCTTATTCCTTTTTGTGCGACCACACGCACGCTGAAAGCTCCTAGTCAACCATTCAGGTT\r\n"
				+ "GTGCGAATCTCCGTGCAAGAACAATTTTGTACGAATTATTCTTGGTGCAGGGCTTCCCTA\r\n"
				+ "TTTATTACTATTGATATCGCGGCGCTCCCCAGATCCCACGTCGCCCTAAGCGTCAACTCC\r\n"
				+ "CTAGAGTCCCCGCTTCACGGTTTCCGCTACAGGATGTATATTCGTGCAGTGACGTATCCT\r\n"
				+ "GTAAGTCTCCTGGACGGTGAAGATGTGCATGGGCGTTTGCCCAAGATCAAGTTTACATGT\r\n"
				+ "ACATGGTCAACACGTGACTAAATTACCCGCACGGCCATCCCTACCGCAGTATTAAGTGTG\r\n"
				+ "GATGATGAATCGCGGACTTCGTCTAGTTTTCTACCGACTACGATAACCTCACTAAGCCAA\r\n"
				+ "ATAGTCATTAGTTACAATCAGGGGCA\r\n"
				+ "";

		Map<String, DNASequence> sequences = FastaReaderHelper.readFastaDNASequence(new ByteArrayInputStream(input.getBytes()));
		boolean firstSequence = true;
		ConcensusMatrix cm = null;
		for (Entry<String, DNASequence> sequenceEntry: sequences.entrySet()) {
			DNASequence sequence = sequenceEntry.getValue();
			if (firstSequence) {
				firstSequence = false;
				cm = new ConcensusMatrix(sequence.getLength());
			}
			for (int i = 0; i < sequence.getLength(); i++) {
				switch (sequence.getCompoundAt(i + 1).getBase()) {
					case "G":
						cm.getG()[i]++;
						break;
					case "A":
						cm.getA()[i]++;
						break;
					case "T":
						cm.getT()[i]++;
						break;
					case "C":
						cm.getC()[i]++;
						break;
				}
			}
		}

		System.out.print("A: ");
		for (int i = 0; i < cm.getA().length; i++) {
			System.out.print(cm.getA()[i] + " ");
		}
		System.out.println();

		System.out.print("C: ");
		for (int i = 0; i < cm.getC().length; i++) {
			System.out.print(cm.getC()[i] + " ");
		}
		System.out.println();

		System.out.print("G: ");
		for (int i = 0; i < cm.getG().length; i++) {
			System.out.print(cm.getG()[i] + " ");
		}
		System.out.println();

		System.out.print("T: ");
		for (int i = 0; i < cm.getT().length; i++) {
			System.out.print(cm.getT()[i] + " ");
		}
		System.out.println();

		StringBuilder concensus = new StringBuilder();
		for (int i = 0; i < cm.getG().length; i++) {
			if (cm.getG()[i] >= cm.getA()[i] && cm.getG()[i] >= cm.getT()[i] && cm.getG()[i] >= cm.getC()[i]) {
				concensus.append('G');
			}
			else if (cm.getA()[i] >= cm.getG()[i] && cm.getA()[i] >= cm.getT()[i] && cm.getA()[i] >= cm.getC()[i]) {
				concensus.append('A');
			}
			else if (cm.getT()[i] >= cm.getG()[i] && cm.getT()[i] >= cm.getA()[i] && cm.getT()[i] >= cm.getC()[i]) {
				concensus.append('T');
			}
			else {
				concensus.append('C');
			}
		}

		System.out.println(concensus);
	}
	
}
